### ISSUE TITLE
Enable 2-level navigation

### ISSUE THREAD

**Issue by jrondorf** [instacks/blankstrap#1]
More difficult than expected. Has to be customised via JS.

https://v4-alpha.getbootstrap.com/components/navbar/#nav

**Comment by jrondorf** [comment]
Use the dropdown toggler link from here:
https://getbootstrap.com/docs/4.0/components/navbar/#nav

More examples for that:
https://bootswatch.com/default/

**Comment by spidercrab** [comment]
How do you add that to the nav declaration using RW.  I tried adding it as html but RW adds it to the  bottom of the body code.  I assume it needs to go at the top or be added some other way.

**Comment by jrondorf** [comment]
I have to build this into the navigation handler itself. It is not straight forward, as you have to define a markup for the additional sub pages, and alter that markup then with JavaScript so that you have correct dropdown links...

**Comment by jrondorf** [comment]
Working on that currently...

**Comment by jrondorf** [comment]
https://github.com/jrondorf/Blankstrap/commit/cd9e2339d3e4a52448466f97684542e9a01c2d2b

**Comment by jrondorf** [comment]
Done!
