### ISSUE TITLE
Add basic stacks

### ISSUE THREAD

**Issue by jrondorf** [instacks/blankstrap#10]

**Comment by jrondorf** [comment]
@spidercrab If you have more ideas for **simple** layout stacks needed by most of the users, please add them here.

**Comment by spidercrab** [comment]
Hi, I have just created a flex box simple vert centred height stack to build simple edge to edge bands.  It used Min Height so will from with the content if needed and also has a padding top and bottom option.  I would have suggested this one. I will let you know. I have been focussed on trying to think of faster ways (in Edit & Preview) of building sites.  These types of stacks would be ideal for using inside Poster for large item setups.

**Comment by spidercrab** [comment]
One thing that is quite difficult for users to do is use Google Fonts and set text sizes without using specialist text stacks.  So a Theme option to choose a Google Font & weight for paragraph and also a different one for headers would be very useful. Also either setting the paragraph default size and then each of the H1 to H6 would be good.  Alternatively, and maybe even better, would to just set the text and H1-H6 for Tablet+ and mobile and also Display sizes D1-D4 in the theme to the same as the default Foundry values which work pretty well.  I.e. No user option to set these but default to a good set of sizes.

**Comment by jrondorf** [comment]
fonts good idea.

What about basic banners, reusing the RW banner feature?

Would love to check the vert centered height.

**Comment by spidercrab** [comment]
I am not sure about Banners because I don't know much about that feature.  I always assumed it only applied to rigid themes that had a banner as a main image at the top of a page, so I can't see how that would relate to a  blank freeform theme.

**Comment by jrondorf** [comment]
- simple div with id and css class
- grid
- button
- card
- carousel
- form
