### ISSUE TITLE
Container width settings

### ISSUE THREAD

**Issue by jrondorf** [instacks/blankstrap#3]
Different container width settings for navigation bar and content.

If content will not have full width, stacks requiring a full width body content will not work.

**Comment by jrondorf** [comment]
Content now has option for no container at all, container, container-fluid.

To add: container width options

**Comment by jrondorf** [comment]
Adding different container options is to much work. This can easily be done by overwriting with custom CSS. Here are the details:
https://getbootstrap.com/docs/4.0/layout/overview/

**Comment by jrondorf** [comment]
none = 100% width

`.container-fluid {
    width: 100%;
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}`

`.container {
    width: 100%;
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
@media (min-width: 1200px)
.container {
    max-width: 1140px;
}
@media (min-width: 992px)
.container {
    max-width: 960px;
}
@media (min-width: 768px)
.container {
    max-width: 720px;
}
@media (min-width: 576px)
.container {
    max-width: 540px;
}`

**Comment by spidercrab** [comment]
Thats fine and easy enough to do
