### ISSUE TITLE
navbar-light bg-inverse

### ISSUE THREAD

**Issue by BetaStacks** [instacks/blankstrap#6]
First, is it supposed to be `navbar-light` or `navbar-lite`? I could see either one being applicable.
Second, should the text be white or a lighter color by default? Right now it is black text on a grey-ish background. This makes it heard to read and I cant imagine anyone not having to change it. 

Cheers!
Brandon
![Nav Menu](http://corlett.net//images/Screen%20Shot%202017-08-14%20at%208.54.38%20AM.png
)

**Comment by jrondorf** [comment]
That are the Bootstrap / Bootswatch defaults.
