### ISSUE TITLE
Add sticky navigation option for navbar

### ISSUE THREAD

**Issue by jrondorf** [instacks/blankstrap#7]

**Comment by spidercrab** [comment]
Great idea

**Comment by spidercrab** [comment]
As the BS4 Nav Bar is so powerful, it would be really useful to be able to add in the extra functionality such as sticky-bar, as a text option to be added to the nav div.  This would allow users to build a more customised Nav Bar without the need for too many checkboxes.

**Comment by jrondorf** [comment]
`<div id="blankstrap-nav" class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark" style="display: flex;">`

**Comment by jrondorf** [comment]
RW Theme config doesn’t allow an input field unfortunately.

**Comment by spidercrab** [comment]
Shame.  That would be a powerful facility.  Maybe just a Sticky checkbox then if possible.

**Comment by djablo74** [comment]
Great project keep it up man! Going to build something with this really soon. 😋

**Comment by jrondorf** [comment]
@djablo74 Great! Looking forward, please keep us informed.

**Comment by jrondorf** [comment]
Sticky navigation bar added, CSS class called fixed-ton in bootstrap 4 beta 2.
